#!/usr/bin/env python3
"""Generate the service worker precache manifest.

Emits sw-manifest.js (a content-hashed list of every shipped asset) and rewrites
the CACHE_VERSION line inside sw.js.

Rewriting sw.js is the point of the exercise: browsers detect a service worker
update by byte-comparing that file. Change sw-manifest.js alone and an
unmodified sw.js never triggers an update, so the fix never reaches anybody.

Run from the repo root, or pass a root: ./tools/build_sw.py [root]
"""
from __future__ import annotations

import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# Directories that exist for development and never ship.
EXCLUDED_DIRS = {
    ".git", ".claude", ".superpowers", "node_modules",
    "docs", "tests", "tools", "archive", "__pycache__",
}

# Files that must never be precached. sw.js is fetched by the browser directly
# and must stay uncached or updates stall; sw-manifest.js is this script's own
# output and is imported by sw.js, not fetched by the page.
EXCLUDED_FILES = {"sw.js", "sw-manifest.js"}

EXCLUDED_SUFFIXES = {".md", ".py", ".sh", ".json5"}
EXCLUDED_EXACT = {
    "package.json", "package-lock.json", "jsconfig.json", ".deployignore", ".gitignore",
}

VERSION_LINE = re.compile(r"^const CACHE_VERSION = '[^']*';.*$", re.MULTILINE)


@dataclass(frozen=True)
class Asset:
    url: str
    rev: str


def file_revision(path: Path) -> str:
    """First 12 hex characters of the file's SHA-256."""
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest[:12]


def collect_files(root: Path) -> list[Asset]:
    assets: list[Asset] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        if path.name in EXCLUDED_FILES or path.name in EXCLUDED_EXACT:
            continue
        if path.suffix in EXCLUDED_SUFFIXES:
            continue
        if path.name.startswith("STATUS-"):
            continue
        assets.append(Asset(url="/" + rel.as_posix(), rev=file_revision(path)))
    return assets


def manifest_version(assets: list[Asset]) -> str:
    """A single hash over every url+rev pair — changes iff any shipped file changes."""
    joined = "\n".join(f"{a.url}:{a.rev}" for a in assets)
    return hashlib.sha256(joined.encode("utf-8")).hexdigest()[:12]


def render_manifest(assets: list[Asset], version: str) -> str:
    entries = ",\n".join(f'  {{ url: "{a.url}", rev: "{a.rev}" }}' for a in assets)
    return (
        "// GENERATED by tools/build_sw.py — do not edit.\n"
        f'self.PRECACHE_VERSION = "{version}";\n'
        f"self.PRECACHE = [\n{entries}\n];\n"
    )


def build(root: Path) -> str:
    assets = collect_files(root)
    version = manifest_version(assets)

    (root / "sw-manifest.js").write_text(render_manifest(assets, version), encoding="utf-8")

    sw_path = root / "sw.js"
    sw = sw_path.read_text(encoding="utf-8")
    replacement = f"const CACHE_VERSION = '{version}'; // build_sw.py rewrites this line"
    updated, count = VERSION_LINE.subn(replacement, sw, count=1)
    if count != 1:
        raise SystemExit("build_sw: could not find the CACHE_VERSION line in sw.js")
    sw_path.write_text(updated, encoding="utf-8")

    print(f"build_sw: {len(assets)} assets, version {version}")
    return version


if __name__ == "__main__":
    build(Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd())
